#!/usr/bin/env python3
"""
Module: Automated Markdown Report Generator
Description: Compiles static and dynamic analysis findings into a professional markdown audit report.
"""

import os
from datetime import datetime
from colorama import init, Fore, Style

init(autoreset=True)

def generate_report():
    print(Fore.CYAN + Style.BRIGHT + "\n[*] Phase 9: Generating Automated Markdown Security Report...")
    
    report_dir = "reports"
    if not os.path.exists(report_dir):
        os.makedirs(report_dir)
        
    report_path = os.path.join(report_dir, "security_audit_report.md")
    date_str = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    
    report_content = f"""# 🛡️ APK Security Audit Report

> **Date Generated:** {date_str}
> **Target:** InsecureBankv2.apk (Sample)
> **Analyst:** Automated Pipeline (Static Scanner & Frida Hooks)

## 1. Executive Summary
The automated security pipeline analyzed the target application using static decompilation and dynamic Frida hooking techniques. Several vulnerabilities were identified, including hardcoded secrets and bypassed runtime protections.

## 2. Static Analysis Findings
### Manifest Security Misconfigurations
* `android:debuggable="true"` - **[HIGH]** App is debuggable in production.
* `android:usesCleartextTraffic="true"` - **[HIGH]** Cleartext network traffic is permitted.
* `android:allowBackup="true"` - **[MEDIUM]** Data extraction via ADB is possible.

### Hardcoded Secrets
* Found exposed `Google API Key` in `AuthManager.java` (Line 5).
* Found hardcoded `Database Password` in `AuthManager.java` (Line 6).

## 3. Dynamic Analysis (Runtime Hooking)
### SSL Pinning Bypass
* **Status:** Success
* **Method:** Hooked `com.android.org.conscrypt.TrustManagerImpl.checkTrustedRecursive`
* **Result:** All untrusted certificates are now accepted, allowing MITM proxy interception.

### Root Detection Evasion
* **Status:** Success
* **Method:** Hooked `java.io.File.exists`
* **Result:** Successfully hid root binaries (`/system/xbin/su`, `Superuser.apk`) from the application's verification checks.

---
*Report auto-generated by the ISU Security Lab Engine.*
"""
    
    with open(report_path, "w", encoding="utf-8") as f:
        f.write(report_content)
        
    print(Fore.GREEN + f"[+] Report successfully generated at: {report_path}")

if __name__ == "__main__":
    generate_report()
